import { Event as EventType } from '../../types/event';

export const sampleEvents: EventType[] = [
  {
    id: '1',
    title: 'Tech Conference 2024',
    description: 'Join us for the biggest tech conference of the year! Featuring keynote speakers, workshops, networking sessions, and the latest innovations in technology. This three-day event brings together industry leaders, developers, and tech enthusiasts from around the world.',
    shortDescription: 'The biggest tech conference of the year with keynote speakers and workshops',
    startDate: '2024-06-15',
    endDate: '2024-06-17',
    startTime: '09:00',
    endTime: '18:00',
    timezone: 'America/New_York',
    location: {
      venue: 'Convention Center',
      address: '123 Tech Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      country: 'USA',
      coordinates: {
        latitude: 37.7749,
        longitude: -122.4194,
      },
    },
    category: 'Technology',
    subcategory: 'Conference',
    organizer: {
      name: 'Tech Events Inc.',
      email: 'info@techevents.com',
      phone: '+1 (555) 123-4567',
      website: 'https://techevents.com',
    },
    images: [
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
      'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800',
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    price: {
      amount: 299,
      currency: 'USD',
      type: 'paid',
    },
    capacity: 1000,
    registeredAttendees: 750,
    tags: ['technology', 'conference', 'networking', 'workshops', 'keynotes'],
    features: [
      'Keynote presentations from industry leaders',
      'Interactive workshops and hands-on sessions',
      'Networking opportunities with professionals',
      'Exhibition hall with latest tech products',
      'Panel discussions on emerging trends',
      'Career fair and job opportunities',
    ],
    status: 'upcoming',
    featured: true,
    registrationRequired: true,
    registrationDeadline: '2024-06-10',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
  },
  {
    id: '2',
    title: 'Yoga & Wellness Retreat',
    description: 'Escape the hustle and bustle of daily life with our rejuvenating yoga and wellness retreat. Experience daily yoga sessions, meditation workshops, healthy meals, and peaceful surroundings in the heart of nature.',
    shortDescription: 'Rejuvenating yoga and wellness retreat in nature',
    startDate: '2024-07-20',
    endDate: '2024-07-22',
    startTime: '08:00',
    endTime: '20:00',
    timezone: 'America/Los_Angeles',
    location: {
      venue: 'Mountain View Resort',
      address: '456 Peaceful Valley Road',
      city: 'Sedona',
      state: 'AZ',
      zipCode: '86336',
      country: 'USA',
      coordinates: {
        latitude: 34.8697,
        longitude: -111.7610,
      },
    },
    category: 'Health & Wellness',
    subcategory: 'Retreat',
    organizer: {
      name: 'Zen Wellness Center',
      email: 'hello@zenwellness.com',
      phone: '+1 (555) 987-6543',
      website: 'https://zenwellness.com',
    },
    images: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    price: {
      amount: 450,
      currency: 'USD',
      type: 'paid',
    },
    capacity: 50,
    registeredAttendees: 35,
    tags: ['yoga', 'wellness', 'retreat', 'meditation', 'nature'],
    features: [
      'Daily yoga sessions for all levels',
      'Meditation and mindfulness workshops',
      'Healthy organic meals included',
      'Nature walks and outdoor activities',
      'Spa treatments and massages',
      'Peaceful accommodation in nature',
    ],
    status: 'upcoming',
    featured: false,
    registrationRequired: true,
    registrationDeadline: '2024-07-15',
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-18T16:45:00Z',
  },
  {
    id: '3',
    title: 'Startup Networking Mixer',
    description: 'Connect with fellow entrepreneurs, investors, and startup enthusiasts in a relaxed networking environment. Share ideas, find potential collaborators, and build valuable business relationships.',
    shortDescription: 'Networking event for entrepreneurs and startup enthusiasts',
    startDate: '2024-05-10',
    endDate: '2024-05-10',
    startTime: '18:00',
    endTime: '21:00',
    timezone: 'America/New_York',
    location: {
      venue: 'Innovation Hub',
      address: '789 Startup Avenue',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    category: 'Business',
    subcategory: 'Networking',
    organizer: {
      name: 'Startup Community',
      email: 'events@startupcommunity.org',
      phone: '+1 (555) 456-7890',
      website: 'https://startupcommunity.org',
    },
    images: [
      'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800',
      'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800',
      'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=400',
    price: {
      amount: 0,
      currency: 'USD',
      type: 'free',
    },
    capacity: 200,
    registeredAttendees: 180,
    tags: ['startup', 'networking', 'entrepreneurship', 'business', 'innovation'],
    features: [
      'Open networking with entrepreneurs',
      'Light refreshments and appetizers',
      'Pitch competition showcase',
      'Investor meet-and-greet',
      'Panel discussion on startup trends',
      'Resource sharing and collaboration opportunities',
    ],
    status: 'upcoming',
    featured: true,
    registrationRequired: true,
    registrationDeadline: '2024-05-08',
    createdAt: '2024-01-05T11:00:00Z',
    updatedAt: '2024-01-22T10:15:00Z',
  },
  {
    id: '4',
    title: 'Art Exhibition Opening',
    description: 'Experience the opening night of our contemporary art exhibition featuring works from local and international artists. Enjoy live music, refreshments, and the opportunity to meet the artists.',
    shortDescription: 'Contemporary art exhibition opening with live music',
    startDate: '2024-04-25',
    endDate: '2024-04-25',
    startTime: '19:00',
    endTime: '23:00',
    timezone: 'America/Chicago',
    location: {
      venue: 'Modern Art Gallery',
      address: '321 Creative Street',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'USA',
    },
    category: 'Arts & Culture',
    subcategory: 'Exhibition',
    organizer: {
      name: 'Modern Art Gallery',
      email: 'info@modernartgallery.com',
      phone: '+1 (555) 789-0123',
      website: 'https://modernartgallery.com',
    },
    images: [
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400',
    price: {
      amount: 25,
      currency: 'USD',
      type: 'paid',
    },
    capacity: 300,
    registeredAttendees: 250,
    tags: ['art', 'exhibition', 'culture', 'opening', 'contemporary'],
    features: [
      'Exclusive first look at new artworks',
      'Meet and greet with featured artists',
      'Live music performance',
      'Wine and cheese reception',
      'Guided tour of the exhibition',
      'Art auction preview',
    ],
    status: 'upcoming',
    featured: false,
    registrationRequired: true,
    registrationDeadline: '2024-04-23',
    createdAt: '2024-01-12T08:30:00Z',
    updatedAt: '2024-01-19T13:20:00Z',
  },
  {
    id: '5',
    title: 'Coding Bootcamp Workshop',
    description: 'Learn the fundamentals of web development in this intensive one-day workshop. Perfect for beginners looking to start their coding journey or professionals wanting to refresh their skills.',
    shortDescription: 'Intensive web development workshop for beginners',
    startDate: '2024-06-08',
    endDate: '2024-06-08',
    startTime: '10:00',
    endTime: '17:00',
    timezone: 'America/Denver',
    location: {
      venue: 'Tech Learning Center',
      address: '654 Code Street',
      city: 'Denver',
      state: 'CO',
      zipCode: '80202',
      country: 'USA',
    },
    category: 'Education',
    subcategory: 'Workshop',
    organizer: {
      name: 'Code Academy',
      email: 'workshops@codeacademy.com',
      phone: '+1 (555) 321-6540',
      website: 'https://codeacademy.com',
    },
    images: [
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400',
    price: {
      amount: 150,
      currency: 'USD',
      type: 'paid',
    },
    capacity: 30,
    registeredAttendees: 25,
    tags: ['coding', 'workshop', 'web-development', 'programming', 'education'],
    features: [
      'Hands-on coding exercises',
      'HTML, CSS, and JavaScript basics',
      'Project-based learning approach',
      'Take-home materials and resources',
      'Certificate of completion',
      'Post-workshop support and community access',
    ],
    status: 'upcoming',
    featured: false,
    registrationRequired: true,
    registrationDeadline: '2024-06-05',
    createdAt: '2024-01-08T14:00:00Z',
    updatedAt: '2024-01-21T09:30:00Z',
  },
  {
    id: '6',
    title: 'Community Charity Run',
    description: 'Join us for our annual charity run to support local community programs. Choose from 5K, 10K, or half-marathon distances. All proceeds go directly to supporting education and healthcare initiatives.',
    shortDescription: 'Annual charity run supporting local community programs',
    startDate: '2024-05-18',
    endDate: '2024-05-18',
    startTime: '07:00',
    endTime: '12:00',
    timezone: 'America/Phoenix',
    location: {
      venue: 'Central Park',
      address: '987 Community Drive',
      city: 'Phoenix',
      state: 'AZ',
      zipCode: '85001',
      country: 'USA',
    },
    category: 'Sports & Fitness',
    subcategory: 'Charity',
    organizer: {
      name: 'Community Foundation',
      email: 'events@communityfoundation.org',
      phone: '+1 (555) 654-3210',
      website: 'https://communityfoundation.org',
    },
    images: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
      'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400',
    price: {
      amount: 35,
      currency: 'USD',
      type: 'donation',
    },
    capacity: 500,
    registeredAttendees: 420,
    tags: ['charity', 'running', 'community', 'fitness', 'fundraising'],
    features: [
      'Multiple distance options (5K, 10K, Half-marathon)',
      'Professional timing and race bibs',
      'Post-race refreshments and awards',
      'Family-friendly activities',
      'Fundraising opportunities',
      'Community celebration and entertainment',
    ],
    status: 'upcoming',
    featured: true,
    registrationRequired: true,
    registrationDeadline: '2024-05-15',
    createdAt: '2024-01-03T16:00:00Z',
    updatedAt: '2024-01-17T12:45:00Z',
  },
];

export const eventCategories = [
  'Technology',
  'Business',
  'Health & Wellness',
  'Arts & Culture',
  'Education',
  'Sports & Fitness',
  'Entertainment',
  'Community',
  'Food & Drink',
  'Travel',
];

export const eventStatuses = [
  'upcoming',
  'ongoing',
  'completed',
  'cancelled',
];
