import { SurveyQuestion } from './types';

export const sampleSurveyQuestions: SurveyQuestion[] = [
  {
    id: '1',
    type: 'radio',
    question: 'What is your age group?',
    required: true,
    options: ['18-24', '25-34', '35-44', '45-54', '55+'],
  },
  {
    id: '2',
    type: 'radio',
    question: 'What is your gender?',
    required: true,
    options: ['Male', 'Female', 'Non-binary', 'Prefer not to say'],
  },
  {
    id: '3',
    type: 'text',
    question: 'What is your occupation?',
    required: false,
    placeholder: 'Enter your current job title or occupation...',
  },
  {
    id: '4',
    type: 'radio',
    question: 'What is your highest level of education?',
    required: true,
    options: ['High School', 'Some College', 'Bachelor\'s Degree', 'Master\'s Degree', 'PhD', 'Other'],
  },
  {
    id: '5',
    type: 'checkbox',
    question: 'Which of the following technologies are you familiar with? (Select all that apply)',
    required: true,
    options: ['JavaScript', 'Python', 'React', 'Node.js', 'SQL', 'AWS', 'Docker', 'Git', 'TypeScript', 'MongoDB'],
    allowMultiple: true,
  },
  {
    id: '6',
    type: 'radio',
    question: 'How many years of experience do you have in your field?',
    required: true,
    options: ['Less than 1 year', '1-3 years', '3-5 years', '5-10 years', 'More than 10 years'],
  },
  {
    id: '7',
    type: 'checkbox',
    question: 'What are your primary interests? (Select all that apply)',
    required: false,
    options: ['Web Development', 'Mobile Development', 'Data Science', 'AI/ML', 'DevOps', 'UI/UX Design', 'Cybersecurity', 'Cloud Computing'],
    allowMultiple: true,
  },
  {
    id: '8',
    type: 'radio',
    question: 'How did you hear about our platform?',
    required: true,
    options: ['Social Media', 'Search Engine', 'Friend/Colleague', 'Advertisement', 'Blog/Article', 'Other'],
  },
  {
    id: '9',
    type: 'textarea',
    question: 'What are your main goals for using our platform?',
    required: true,
    placeholder: 'Please describe your objectives and what you hope to achieve...',
    rows: 4,
    maxLength: 300,
  },
  {
    id: '10',
    type: 'radio',
    question: 'How likely are you to recommend our platform to others?',
    required: true,
    options: ['Very Unlikely', 'Unlikely', 'Neutral', 'Likely', 'Very Likely'],
  },
  {
    id: '11',
    type: 'checkbox',
    question: 'Which features would you like to see in future updates? (Select all that apply)',
    required: false,
    options: ['Advanced Analytics', 'Mobile App', 'API Integration', 'Custom Themes', 'Team Collaboration', 'Advanced Search', 'Export Options', 'Real-time Notifications'],
    allowMultiple: true,
  },
  {
    id: '12',
    type: 'textarea',
    question: 'Do you have any additional comments or suggestions?',
    required: false,
    placeholder: 'Share your thoughts, feedback, or suggestions...',
    rows: 3,
    maxLength: 200,
  },
  {
    id: '13',
    type: 'radio',
    question: 'How often do you use our platform?',
    required: true,
    options: ['Daily', 'Weekly', 'Monthly', 'Rarely', 'First time'],
  },
  {
    id: '14',
    type: 'radio',
    question: 'What device do you primarily use?',
    required: false,
    options: ['Desktop', 'Laptop', 'Tablet', 'Mobile', 'Other'],
  },
  {
    id: '15',
    type: 'checkbox',
    question: 'Which browsers do you use? (Select all that apply)',
    required: false,
    options: ['Chrome', 'Firefox', 'Safari', 'Edge', 'Opera', 'Other'],
    allowMultiple: true,
  },
  {
    id: '16',
    type: 'text',
    question: 'What is your preferred contact method?',
    required: false,
    placeholder: 'Email, phone, chat, etc...',
  },
];

export const surveySteps = ['Personal Information', 'Professional Background', 'Platform Feedback', 'Additional Comments'];
