import { SearchResult } from './types';

export const mockSearchResults: SearchResult[] = [
  {
    id: '1',
    title: 'Getting Started with React Development',
    description: 'A comprehensive guide to setting up your first React project with modern tooling and best practices.',
    type: 'article',
    tags: ['React', 'JavaScript', 'Frontend', 'Development'],
    author: 'John Doe',
    date: '2024-01-15',
    readTime: '5 min read',
  },
  {
    id: '2',
    title: 'Advanced TypeScript Patterns',
    description: 'Explore advanced TypeScript patterns and techniques for building scalable applications.',
    type: 'article',
    tags: ['TypeScript', 'Programming', 'Advanced'],
    author: 'Jane Smith',
    date: '2024-01-10',
    readTime: '8 min read',
  },
  {
    id: '3',
    title: 'UI Component Library',
    description: 'A collection of reusable UI components built with Material-UI and React.',
    type: 'resource',
    tags: ['UI', 'Components', 'Material-UI', 'React'],
    author: 'Design Team',
    date: '2024-01-08',
    readTime: '3 min read',
  },
  {
    id: '4',
    title: 'API Integration Best Practices',
    description: 'Learn the best practices for integrating external APIs into your applications.',
    type: 'article',
    tags: ['API', 'Integration', 'Backend', 'REST'],
    author: 'Mike Johnson',
    date: '2024-01-05',
    readTime: '6 min read',
  },
  {
    id: '5',
    title: 'Performance Optimization Guide',
    description: 'Comprehensive guide to optimizing React application performance.',
    type: 'resource',
    tags: ['Performance', 'Optimization', 'React', 'Frontend'],
    author: 'Performance Team',
    date: '2024-01-03',
    readTime: '10 min read',
  },
  {
    id: '6',
    title: 'State Management with Redux Toolkit',
    description: 'Modern state management using Redux Toolkit for React applications.',
    type: 'article',
    tags: ['Redux', 'State Management', 'React', 'Toolkit'],
    author: 'Sarah Wilson',
    date: '2024-01-01',
    readTime: '7 min read',
  },
];
